services:
    _defaults:
        autowire: true
        autoconfigure: true

    Goulaheau\RestBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # Services
    goulaheau.rest.serializer: { class: Goulaheau\RestBundle\Core\RestSerializer }
    goulaheau.rest.validator: { class: Goulaheau\RestBundle\Core\RestValidator }

    # Normalizers
    Goulaheau\RestBundle\Normalizer\EntityNormalizer:
        tags: [serializer.normalizer]

    # Listeners
    Goulaheau\RestBundle\EventListener\JsonRequestTransformerListener:
        tags: [{ name: kernel.event_listener, event: kernel.request }]

    Goulaheau\RestBundle\EventListener\RestEntitySubscriber:
        tags: [name: doctrine.event_subscriber]

    # Defaults Dependency Injection
    Goulaheau\RestBundle\Controller\RestController:
        autoconfigure: false
        abstract: true
        calls:
            - [setSerializer, ['@goulaheau.rest.serializer']]
            - [setLogger, ['@logger']]

    Goulaheau\RestBundle\Service\RestService:
        autoconfigure: false
        abstract: true
        calls:
            - [setSerializer, ['@goulaheau.rest.serializer']]
            - [setFilter, ['@dms.filter.inner.filter']]
            - [setValidator, ['@goulaheau.rest.validator']]
            - [setManager, ['@doctrine.orm.entity_manager']]
