services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Goulaheau\RestBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Symfony\Component\Serializer\Normalizer\DateTimeNormalizer:
        tags: [serializer.normalizer]

    Goulaheau\RestBundle\Normalizer\EntityNormalizer:
        tags: [serializer.normalizer]

#    get_set_method_normalizer:
#        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
#        public: false
#        tags: [serializer.normalizer]

    Goulaheau\RestBundle\EventListener\RestEntitySubscriber:
        tags: [name: doctrine.event_subscriber]
