services:
    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        public: false
        tags: [serializer.normalizer]

    Goulaheau\RestBundle\EventListener\RestEntitySubscriber:
        tags:
            - { name: doctrine.event_subscriber }
