services:
    Goulaheau\RestBundle\Normalizer\EntityNormalizer:
        public: false
        autowire: true
        autoconfigure: true
        tags: [serializer.normalizer]

#    get_set_method_normalizer:
#        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
#        public: false
#        tags: [serializer.normalizer]

    Goulaheau\RestBundle\EventListener\RestEntitySubscriber:
        tags: [name: doctrine.event_subscriber]
